### ISSUE TITLE
async-messaged does not respect --log-dir

### ISSUE THREAD

**Issue by boffman** [Biometria-se/grizzly#283]
**Describe the bug**
When running `grizzly-cli dist run ..` with `--log-dir` argument, the async-messaged log is still written to `features/logs/`

**To Reproduce**
1. Run a test, that utilizes async-messaged, with custom log dir specified, e.g. `grizzly-cli dist run --log-dir my_log_dir features/my_feature.feature`
2. Observe that the async-messaged log file is created under `features/logs/`

**Expected behavior**
The async-messaged log should be created under `features/logs/my_log_dir/`

**Desktop (please complete the following information):**
 - OS: Red Hat Enterprise Linux 8.8 (Ootpa)
 - Version
grizzly-cli 3.2.2
└── grizzly 2.7.5.dev3 ── extras: mq
    └── locust >=2.16.0,<2.17.0

**Comment by mgor** [comment]
fixed by #287.
