### ISSUE TITLE
Aborting test can fail when running distributed with MQ

### ISSUE THREAD

**Issue by boffman** [Biometria-se/grizzly#323]
**Describe the bug**
When running a distributed test, where a MQ queue is consumed with e.g. message.wait of 3600, aborting the test fails if it's waiting for a message to consume. The first CTRL+Cs don't work, and the third gets back to the prompt, but with the docker containers still running.

**To Reproduce**
1. Create a test with a MessageQueue user, consuming messages from an empty queue. Set a high message wait.
2. Start the test, distributed
3. Try to abort it
4. Notice that the containers are still running with `docker ps` after 3 CTRL+C:s

**Expected behavior**
The test should be able to interrupt the ongoing MQ message consuming and "finish nicely"

**Comment by mgor** [comment]
this was two problems:
1. when `async-messaged` does a GET on a queue (via the native ibm mq libraries), that call is blocking until `message_wait` and it is not possible to interrupt it earlier. so if there is a timeout on 3600 (1h), it will be blocking for that long
2. the client side does not understand when the server goes away, and it will try to receive messages in an infinite loop.
