### ISSUE TITLE
grizzly: diffrent action depending on type of fault

### ISSUE THREAD

**Issue by mgor** [Biometria-se/grizzly#328]
**Is your feature request related to a problem? Please describe.**
Right now it is possible to choose 1 of 3 ways to handle a failure:
- just continue
- stop user
- restart scenario

**Describe the solution you'd like**
There are cases when one would want different action depending on the type of failure.
So a way of setting what would happend for a specific exception type and/or message.

**Describe alternatives you've considered**
N/A.

**Comment by boffman** [comment]
Extra sugar on top would be:
* stop test
