### ISSUE TITLE
run grizzly on windows

### ISSUE THREAD

**Issue by tuddilue** [Biometria-se/grizzly#57]
I have installed grizzly-loadtest and grizzly-loadtester-cli on windows without problems.
One note is that C++ is huge to install setproctitle. That maybe you can look into as well?

But the problem I got when running yours example is this:

C:\Users\Pelle\PycharmProjects\grizzly-main\example> grizzly-cli --local -c environments/example.yaml features/example.feature
Traceback (most recent call last):
  File "C:\Users\Pelle\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Pelle\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Pelle\PycharmProjects\grizzly-main\venv\Scripts\grizzly-cli.exe\__main__.py", line 4, in <module>
  File "c:\users\pelle\pycharmprojects\grizzly-main\venv\lib\site-packages\grizzly_cli\cli.py", line 21, in <module>
    from .build import main as build
  File "c:\users\pelle\pycharmprojects\grizzly-main\venv\lib\site-packages\grizzly_cli\build.py", line 1, in <module>
    from os import environ, getuid, getgid
ImportError: cannot import name 'getuid' from 'os' (C:\Users\Pelle\AppData\Local\Programs\Python\Python310\lib\os.py)
PS C:\Users\Pelle\PycharmProjects\grizzly-main\example>

So os.py needs to be handled for windows user. Can you give me some tips?

**Comment by mgor** [comment]
we're in the middle of a big rewrite of `grizzly-cli`, when that is done I'll have a look at adding support for running it in windows as well.

**Comment by boffman** [comment]
.. Until then, please run it in [WSL](https://docs.microsoft.com/en-us/windows/wsl/install), or Linux, if possible !

**Comment by tuddilue** [comment]
Sounds good. Look into why you need setproctitle as well. Because C++ installation is 6gb on windows

On this cooperation we do not have access till linux...

**Comment by mgor** [comment]
> Sounds good. Look into why you need setproctitle as well. Because C++ installation is 6gb on windows
> 

setproctitle is used to get correct application/process name (would otherwise be behave).

Main usage is though together with pymqi to get/put messages on IBM MQ, so I guess it could be moved as an optional with pymqi. That would be a separate issue though.

**Comment by tuddilue** [comment]
Aha to be honest I didn't check it up. But the name of it almost describe what it does. Set proc title :)

Ok I understand. Have it in minde if you see the oportunity to remove it or change it to something else...

**Comment by mgor** [comment]
`grizzly-loadtester-cli==2.0.0` has now been released, and it works running, the example, on windows.

a lot of other stuff has changed as well, and I haven't had time to update the CLI or example documentation yet. Everything up until actually executing the example is the same, and then:

```grizzly-cli run -e .\environments\example.yaml local .\features\example.feature```

due to this, i'm closing the issue.
the "problem" with `setproctitle`, I would say is a minor inconvience. I had a quick look for an alternative, but couldn't find one.
please open up a seperate issue if it is something that we should really spend time on.
